# -*- coding: utf-8 -*-
"""BulychevaEV_DZ12_Tema13_KOD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wL8eee-YKOZ1jmPs0wDhYBOrxUg650YK
"""

pip install scapy

from scapy.all import *

packets = rdpcap('dhcp.pcapng')
dns_queries = []
ip_addresses = set()

for packet in packets:
    if packet.haslayer(DNSQR):
        dns_queries.append({
            'time': packet.time,
            'query': packet[DNSQR].qname.decode('utf-8')
        })
    if packet.haslayer(IP):
        ip_addresses.add(packet[IP].src)
        ip_addresses.add(packet[IP].dst)

print(f"DNS-запросы: {len(dns_queries)}")
print(f"IP-адреса: {len(ip_addresses)}")

from scapy.all import *

packets = rdpcap('dhcp.pcapng')
for i, packet in enumerate(packets):
    print(f"Пакет {i}: {packet.summary()}")

print("Список IP-адресов:")
for ip in ip_addresses:
    print(ip)

import matplotlib.pyplot as plt
import pandas as pd

# Создаём DataFrame с временем и IP
data = []
for packet in packets:
    if packet.haslayer(IP):
        data.append({
            'time': packet.time,
            'src_ip': packet[IP].src,
            'dst_ip': packet[IP].dst
        })

df = pd.DataFrame(data)
df['time'] = pd.to_datetime(df['time'], unit='s')

# График активности по времени
plt.figure(figsize=(12, 6))
df.set_index('time').resample('1T').size().plot(kind='line', title='Активность IP-адресов по времени')
plt.xlabel('Время')
plt.ylabel('Количество пакетов')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
from scapy.all import *

# Загружаем пакеты
packets = rdpcap('dhcp.pcapng')

# Собираем данные
data = []
for packet in packets:
    if packet.haslayer(IP):
        data.append({
            'time': packet.time,
            'src_ip': packet[IP].src,
            'dst_ip': packet[IP].dst
        })

# Создаём DataFrame
df = pd.DataFrame(data)

# Преобразуем время в datetime
df['time'] = pd.to_datetime(df['time'], unit='s', errors='coerce')

# Удаляем строки с NaT (если есть)
df = df.dropna(subset=['time'])

# График активности по времени
plt.figure(figsize=(12, 6))
df.set_index('time').resample('1T').size().plot(kind='line', title='Активность IP-адресов по времени')
plt.xlabel('Время')
plt.ylabel('Количество пакетов')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
from scapy.all import *

# Загружаем пакеты
packets = rdpcap('dhcp.pcapng')

# Собираем данные
data = []
for packet in packets:
    if packet.haslayer(IP):
        data.append({
            'time': float(packet.time),  # Убедитесь, что это число
            'src_ip': packet[IP].src,
            'dst_ip': packet[IP].dst
        })

# Создаём DataFrame
df = pd.DataFrame(data)

# Преобразуем время в datetime
df['time'] = pd.to_datetime(df['time'], unit='s', errors='coerce')

# Удаляем строки с NaT (если есть)
df = df.dropna(subset=['time'])

# Проверяем, что DataFrame не пустой
if df.empty:
    print("DataFrame пуст! Проверьте данные.")
else:
    print("Первые 5 строк DataFrame:")
    print(df.head())

    # График активности по времени
    plt.figure(figsize=(12, 6))
    df.set_index('time').resample('1min').size().plot(kind='line', title='Активность IP-адресов по времени')
    plt.xlabel('Время')
    plt.ylabel('Количество пакетов')
    plt.grid(True)
    plt.show()